services:

  production:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ga_timetabling_production
    volumes:
      - ./outputs:/app/outputs
    command: python main.py --seed 42 --soft-local-search

  web-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ga_timetabling_web_ui
    ports:
      - "8501:8501"
    volumes:
      - ./outputs:/app/outputs
    command: streamlit run ui_app.py --server.headless true --server.port 8501 --server.address 0.0.0.0

  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ga_timetabling_benchmark
    volumes:
      - ./outputs:/app/outputs
    command: python main_benchmark.py --mode fast

  test-ga:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ga_timetabling_test
    volumes:
      - ./outputs:/app/outputs
    command: pytest -q
